name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-java-lib:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - x64
          - x86
        java:
          - "8"
          - "11"
          - "16"
          - "17"
        distribution:
          - temurin
          - zulu
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          architecture: ${{ matrix.arch }}
      - name: Setup Mecab-ko-msvc
        run: |
          curl -fSL -o 'mecab-ko-msvc-${{ matrix.arch }}.zip'  'https://github.com/Pusnow/mecab-ko-msvc/releases/download/release-0.9.2-msvc-3/mecab-ko-msvc-${{ matrix.arch }}.zip'
          7z x mecab-ko-msvc-${{ matrix.arch }}.zip -oc:\mecab
      - name: Build Java Library
        run: |
          cl.exe /EHsc /O2 /GL /GA /Ob2 /nologo /W3 /MT /Zi /wd4800 /wd4305 /wd4244 -I"$env:JAVA_HOME\include" -I"$env:JAVA_HOME\include\win32" -I"C:\mecab" -c MeCab_wrap.cxx
          link.exe /nologo /OPT:REF /OPT:ICF /LTCG /NXCOMPAT /DYNAMICBASE /MACHINE:${{ matrix.arch }} -out:MeCab.dll C:\mecab\libmecab.lib MeCab_wrap.obj /dll
      - name: 7z
        run: 7z a mecab-java-msvc-${{ matrix.distribution }}-${{ matrix.java }}-${{ matrix.arch }}.zip MeCab.dll org\ test.java
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: mecab-java-msvc-${{ matrix.distribution }}-${{ matrix.java }}-${{ matrix.arch }}.zip